import os, datetime, pandas as pd

path = '/Users/nrivard/Work Vault' # 'C:\\Users\\2020745.UK\\OneDrive - EY\Work Vault'
os.chdir(path)

listOfDates = pd.date_range(start="2026-01-01",end="2026-12-31").tolist()

for date in listOfDates:
    delta1 = datetime.timedelta(1)
    delta2 = datetime.timedelta(2)
    delta3 = datetime.timedelta(3)
    delta4 = datetime.timedelta(4)
    delta5 = datetime.timedelta(5)
    delta6 = datetime.timedelta(6)
    delta7 = datetime.timedelta(7)
    yesterdayWeekNumber = (date - delta1).strftime("%Y W%W") # 2021 W32
    dayOfWeekNumber = date.dayofweek # 0
    if dayOfWeekNumber == 0:
        mo = date.strftime("%y%m%d %A")
        tu = (date + delta1).strftime("%y%m%d %A")
        we = (date + delta2).strftime("%y%m%d %A")
        th = (date + delta3).strftime("%y%m%d %A")
        fr = (date + delta4).strftime("%y%m%d %A")
        sa = (date + delta5).strftime("%y%m%d %A")
        su = (date + delta6).strftime("%y%m%d %A")
        monday = date.strftime("%y%m%d")
        tuesday = (date + delta1).strftime("%y%m%d")
        wednesday = (date + delta2).strftime("%y%m%d")
        thursday = (date + delta3).strftime("%y%m%d")
        friday = (date + delta4).strftime("%y%m%d")
        saturday = (date + delta5).strftime("%y%m%d")
        sunday = (date + delta6).strftime("%y%m%d")
    if dayOfWeekNumber == 1:
        mo = (date - delta1).strftime("%y%m%d %A")
        tu = date.strftime("%y%m%d %A")
        we = (date + delta1).strftime("%y%m%d %A")
        th = (date + delta2).strftime("%y%m%d %A")
        fr = (date + delta3).strftime("%y%m%d %A")
        sa = (date + delta4).strftime("%y%m%d %A")
        su = (date + delta5).strftime("%y%m%d %A")
        monday = (date - delta1).strftime("%y%m%d")
        tuesday = date.strftime("%y%m%d")
        wednesday = (date + delta1).strftime("%y%m%d")
        thursday = (date + delta2).strftime("%y%m%d")
        friday = (date + delta3).strftime("%y%m%d")
        saturday = (date + delta4).strftime("%y%m%d")
        sunday = (date + delta5).strftime("%y%m%d")
    if dayOfWeekNumber == 2:
        mo = (date - delta2).strftime("%y%m%d %A")
        tu = (date - delta1).strftime("%y%m%d %A")
        we = date.strftime("%y%m%d %A")
        th = (date + delta1).strftime("%y%m%d %A")
        fr = (date + delta2).strftime("%y%m%d %A")
        sa = (date + delta3).strftime("%y%m%d %A")
        su = (date + delta4).strftime("%y%m%d %A")
        monday = (date - delta2).strftime("%y%m%d")
        tuesday = (date - delta1).strftime("%y%m%d")
        wednesday = date.strftime("%y%m%d")
        thursday = (date + delta1).strftime("%y%m%d")
        friday = (date + delta2).strftime("%y%m%d")
        saturday = (date + delta3).strftime("%y%m%d")
        sunday = (date + delta4).strftime("%y%m%d")
    if dayOfWeekNumber == 3:
        mo = (date - delta3).strftime("%y%m%d %A")
        tu = (date - delta2).strftime("%y%m%d %A")
        we = (date - delta1).strftime("%y%m%d %A")
        th = date.strftime("%y%m%d %A")
        fr = (date + delta1).strftime("%y%m%d %A")
        sa = (date + delta2).strftime("%y%m%d %A")
        su = (date + delta3).strftime("%y%m%d %A")
        monday = (date - delta3).strftime("%y%m%d")
        tuesday = (date - delta2).strftime("%y%m%d")
        wednesday = (date - delta1).strftime("%y%m%d")
        thursday = date.strftime("%y%m%d")
        friday = (date + delta1).strftime("%y%m%d")
        saturday = (date + delta2).strftime("%y%m%d")
        sunday = (date + delta3).strftime("%y%m%d")
    if dayOfWeekNumber == 4:
        mo = (date - delta4).strftime("%y%m%d %A")
        tu = (date - delta3).strftime("%y%m%d %A")
        we = (date - delta2).strftime("%y%m%d %A")
        th = (date - delta1).strftime("%y%m%d %A")
        fr = date.strftime("%y%m%d %A")
        sa = (date + delta1).strftime("%y%m%d %A")
        su = (date + delta2).strftime("%y%m%d %A")
        monday = (date - delta4).strftime("%y%m%d")
        tuesday = (date - delta3).strftime("%y%m%d")
        wednesday = (date - delta2).strftime("%y%m%d")
        thursday = (date - delta1).strftime("%y%m%d")
        friday = date.strftime("%y%m%d")
        saturday = (date + delta1).strftime("%y%m%d")
        sunday = (date + delta2).strftime("%y%m%d")        
    if dayOfWeekNumber == 5:
        mo = (date - delta5).strftime("%y%m%d %A")
        tu = (date - delta4).strftime("%y%m%d %A")
        we = (date - delta3).strftime("%y%m%d %A")
        th = (date - delta2).strftime("%y%m%d %A")
        fr = (date - delta1).strftime("%y%m%d %A")
        sa = date.strftime("%y%m%d %A")
        su = (date + delta1).strftime("%y%m%d %A")
        monday = (date - delta5).strftime("%y%m%d")
        tuesday = (date - delta4).strftime("%y%m%d")
        wednesday = (date - delta3).strftime("%y%m%d")
        thursday = (date - delta2).strftime("%y%m%d")
        friday = (date - delta1).strftime("%y%m%d")
        saturday = date.strftime("%y%m%d")
        sunday = (date + delta1).strftime("%y%m%d")
    if dayOfWeekNumber == 6:
        mo = (date - delta6).strftime("%y%m%d %A")
        tu = (date - delta5).strftime("%y%m%d %A")
        we = (date - delta4).strftime("%y%m%d %A")
        th = (date - delta3).strftime("%y%m%d %A")
        fr = (date - delta2).strftime("%y%m%d %A")
        sa = (date - delta1).strftime("%y%m%d %A")
        su = date.strftime("%y%m%d %A")
        monday = (date - delta6).strftime("%y%m%d")
        tuesday = (date - delta5).strftime("%y%m%d")
        wednesday = (date - delta4).strftime("%y%m%d")
        thursday = (date - delta3).strftime("%y%m%d")
        friday = (date - delta2).strftime("%y%m%d")
        saturday = (date - delta1).strftime("%y%m%d")
        sunday = date.strftime("%y%m%d")
    if (date - delta1).strftime("%Y W%W") == date.strftime("%Y W%W"):
        pass
    else:
        last_week = (date - delta1).strftime("%Y W%W")
        this_week = date.strftime("%Y W%W")
        next_week = (date + delta7).strftime("%Y W%W")
        weeklyNoteText = '---\naliases: [' + monday + ' - ' + sunday + ']\n---\n\n[[' + last_week + '|<< Last week]] | [[' + next_week + '|Next week >>]]\n\n# Priori-threes\n1. \n2. \n3. \n\n# Actions\n\n##### This Week\n\n```query\nline: ("[ ]" -"line:") ("' + this_week + '" OR (file: ("' + monday + '" OR "' + tuesday + '" OR "' + wednesday + '" OR "' + thursday + '" OR "' + friday + '")))\n```\n\n##### Other\n\n```query\n/(20[2-9][0-9] W[0-5][0-9])/ -"' + this_week + '" line: ("[ ]" -"line:")\n```\n\n# Planner\n\n##### This Week\n\n[[' + mo + ']]\n[[' + tu + ']]\n[[' + we + ']]\n[[' + th + ']]\n[[' + fr + ']]\n\n##### Other\n\n```query\n\n(line: ("' + this_week + '" -"line:") OR (file: "' + monday + '" OR "' + tuesday + '" OR "' + wednesday + '" OR "' + thursday + '" OR "' + friday + '")) file: -("' + monday + '" OR "' + tuesday + '" OR "' + wednesday + '" OR "' + thursday + '" OR "' + friday + '" OR /(20[2-9][0-9] W[0-5][0-9])/)\n```\n\n# Completed\n\n### This Week\n\n```query\n"' + this_week + '" line: ("[x]" -"line:")\n```\n\n---\nTags: \n'
        title = date.strftime("%Y W%W")
        with open(str(title) + ".md", 'w') as newFile:
            print(weeklyNoteText, file=newFile)
